In [2]:
# Import packages
import pandas as pd
import os
import numpy as np

## 1. Archive Exploration
Look through the dataset’s description in the ScienceBase repository. Find the following information:

i. Where was the data collected from?

Data was collected from the Colorado River Basin (mostly Upper Colorado River Basin).

ii. During what time frame were the observations in the dataset collected?

Observations in the dataset were collected from 2005-2021.

iii. What was the author’s perceived value of this dataset?

The author perceived the dataset as valuable because it provides some understanding of the social vulnerability to water insecurity, and the conflict or crisis around water resource managemet as it relates to the Colorado River Basin.

# 3. Preliminary data exploration

In [27]:
# Download data
df = pd.read_csv('data/Colorado River Basin Water Conflict Table.csv')
df

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,264,USGS301-350.docx,The Durango Herald (Colorado),Water officials consider action for worst case...,False,9-Jun-09,2019.0,6,NaN,6.0,2019.0,N,Y,Colorado Headwaters,140100,14,"Western Slope, CO",NaN,NaN,CO,8,Both,Water rights more generally,Board members of the Southwestern Waer Conserv...,"NGO, Conservation District, Agriculture, Business",0.0,Scored based on the fact that the discussion w...,NaN,0,0,3,3,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
264,265,USGS301-350.docx,"Rio Blanco Herald Times (Meeker, Colorado)",Rangely hosts Colorado River District event,False,21-Apr-22,2022.0,4/13/2022,13.0,4.0,2022.0,N,Y,Entire Colorado River Basin,NaN,"14, 15","Western Slope, CO",NaN,NaN,CO,8,Both,Drought; Water quality; Water rights more gene...,The event is a 'State of the River' event invo...,"Conservancy District, State Government, All Wa...",0.0,No true conflicts explored at this event. Pure...,NaN,2,1,5,0,0,0,0,1,0,0,3,0,0,0,0,1,1,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,AZ; CA,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
266,267,USGS301-350.docx,The Salt Lake Tribune,Scientists want to flush water past Glen Canyo...,False,13-Dec-07,2007.0,12,NaN,12.0,2007.0,N,N,Entire Colorado River Basin,NaN,"14, 15","Glen Canyon Dam, AZ",NaN,NaN,AZ,4,Both,Conservation,Dept of Interior Secretary Dirk Kempthorne sig...,"All Water Users, Environment",5.0,Scored 5 based on the agreement to protect the...,NaN,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0
267,268,USGS301-350.docx,Casa Grande Dispatch (AZ),Arizona plan could devastate Pinal farmers,NaN,2-Feb-19,2019.0,1/31/2019,31.0,1.0,2019.0,N,Y,Entire Colorado River Basin,NaN,"14, 15",State of Arizona,NaN,NaN,AZ,4,Both,Conservation; Ground water depletion,The event is Arizona signing off on the Drough...,"Agriculture, State Government, Federal Government",4.0,Agreement signed and cooperation on all sides...,NaN,1,0,0,10,0,0,0,1,0,0,2,0,0,0,0,0,0,0,0,0

In [28]:
# View first 5 rows
df.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0

In [29]:
type(df)

pandas.core.frame.DataFrame

In [30]:
# View columns
pd.set_option("display.max_columns", None)
df

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,264,USGS301-350.docx,The Durango Herald (Colorado),Water officials consider action for worst case...,False,9-Jun-09,2019.0,6,NaN,6.0,2019.0,N,Y,Colorado Headwaters,140100,14,"Western Slope, CO",NaN,NaN,CO,8,Both,Water rights more generally,Board members of the Southwestern Waer Conserv...,"NGO, Conservation District, Agriculture, Business",0.0,Scored based on the fact that the discussion w...,NaN,0,0,3,3,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
264,265,USGS301-350.docx,"Rio Blanco Herald Times (Meeker, Colorado)",Rangely hosts Colorado River District event,False,21-Apr-22,2022.0,4/13/2022,13.0,4.0,2022.0,N,Y,Entire Colorado River Basin,NaN,"14, 15","Western Slope, CO",NaN,NaN,CO,8,Both,Drought; Water quality; Water rights more gene...,The event is a 'State of the River' event invo...,"Conservancy District, State Government, All Wa...",0.0,No true conflicts explored at this event. Pure...,NaN,2,1,5,0,0,0,0,1,0,0,3,0,0,0,0,1,1,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,AZ; CA,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
266,267,USGS301-350.docx,The Salt Lake Tribune,Scientists want to flush water past Glen Canyo...,False,13-Dec-07,2007.0,12,NaN,12.0,2007.0,N,N,Entire Colorado River Basin,NaN,"14, 15","Glen Canyon Dam, AZ",NaN,NaN,AZ,4,Both,Conservation,Dept of Interior Secretary Dirk Kempthorne sig...,"All Water Users, Environment",5.0,Scored 5 based on the agreement to protect the...,NaN,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0
267,268,USGS301-350.docx,Casa Grande Dispatch (AZ),Arizona plan could devastate Pinal farmers,NaN,2-Feb-19,2019.0,1/31/2019,31.0,1.0,2019.0,N,Y,Entire Colorado River Basin,NaN,"14, 15",State of Arizona,NaN,NaN,AZ,4,Both,Conservation; Ground water depletion,The event is Arizona signing off on the Drough...,"Agriculture, State Government, Federal Government",4.0,Agreement signed and cooperation on all sides...,NaN,1,0,0,10,0,0,0,1,0,0,2,0,0,0,0,0,0,0,0,0

In [31]:
# High-level info view
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Event                                         268 non-null    int64
 1   Search Source                                 268 non-null    object
 2   Newspaper                                     268 non-null    object
 3   Article Title                                 268 non-null    object
 4   Duplicate                                     267 non-null    object
 5   Report Date                                   267 non-null    object
 6   Report Year                                   265 non-null    float64
 7   Event Date                                    248 non-null    object
 8   Event Day                                     18 non-null     float64
 9   Event Month                                   212 non-null    float64
 10  Event Year                                    257 non-null    float64
 11  Conflict Present                              252 non-null    object
 12  Crisis Present                                254 non-null    object
 13  Basin                                         250 non-null    object
 14  HUC6                                          110 non-null    object
 15  HUC2                                          250 non-null    object
 16  Place                                         254 non-null    object
 17  County                                        8 non-null      object
 18  County FIPS                                   8 non-null      float64
 19  State                                         178 non-null    object
 20  State FIPS                                    178 non-null    object
 21  Urban or Rural                                254 non-null    object
 22  Issue Type                                    255 non-null    object
 23  Event Summary                                 256 non-null    object
 24  Stakeholders                                  255 non-null    object
 25  Intensity Value                               255 non-null    float64
 26  Comments                                      190 non-null    object
 27  Related Observation Themes                    86 non-null     object
 28  Article Text Search - water quality           268 non-null    int64
 29  Article Text Search - invasive species        268 non-null    int64
 30  Article Text Search - conservation            268 non-null    int64
 31  Article Text Search - drought                 268 non-null    int64
 32  Article Text Search - flood                   268 non-null    int64
 33  Article Text Search - ground water depletion  268 non-null    int64
 34  Article Text Search - depletion               268 non-null    int64
 35  Article Text Search - infrastructure          268 non-null    int64
 36  Article Text Search - fish passage            268 non-null    int64
 37  Article Text Search - instream water rights   268 non-null    int64
 38  Article Text Search - water rights            268 non-null    int64
 39  Article Text Search - intergovernmental       268 non-null    int64
 40  Article Text Search - water transfers         268 non-null    int64
 41  Article Text Search - navigation              268 non-null    int64
 42  Article Text Search - fish                    268 non-null    int64
 43  Article Text Search - invasive                268 non-null    int64
 44  Article Text Search - diversion               268 non-null    int64
 45  Article Text Search - water diversion         268 non-null    int64
 46  Article Text Search - instream                268 non-null    int64
 47  Article Text Search - aquatic                 268 non-null    int64
dtypes: float64(6), int64(21), object(21)
memory usage: 100.6+ KB

In [32]:
# View last rows
df.tail()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
263,264,USGS301-350.docx,The Durango Herald (Colorado),Water officials consider action for worst case...,False,9-Jun-09,2019.0,6,NaN,6.0,2019.0,N,Y,Colorado Headwaters,140100,14,"Western Slope, CO",NaN,NaN,CO,8,Both,Water rights more generally,Board members of the Southwestern Waer Conserv...,"NGO, Conservation District, Agriculture, Business",0.0,Scored based on the fact that the discussion w...,NaN,0,0,3,3,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0
264,265,USGS301-350.docx,"Rio Blanco Herald Times (Meeker, Colorado)",Rangely hosts Colorado River District event,False,21-Apr-22,2022.0,4/13/2022,13.0,4.0,2022.0,N,Y,Entire Colorado River Basin,NaN,"14, 15","Western Slope, CO",NaN,NaN,CO,8,Both,Drought; Water quality; Water rights more gene...,The event is a 'State of the River' event invo...,"Conservancy District, State Government, All Wa...",0.0,No true conflicts explored at this event. Pure...,NaN,2,1,5,0,0,0,0,1,0,0,3,0,0,0,0,1,1,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,2019.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15","State of Arizona, State of California",NaN,NaN,AZ; CA,04; 06,Both,Intergovernmental issues,The event is that California's Imperial Irriga...,"All Water Users, Agriculture, State Government...",-4.0,Scored based on the fact that the event is act...,NaN,1,0,3,9,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0
266,267,USGS301-350.docx,The Salt Lake Tribune,Scientists want to flush water past Glen Canyo...,False,13-Dec-07,2007.0,12,NaN,12.0,2007.0,N,N,Entire Colorado River Basin,NaN,"14, 15","Glen Canyon Dam, AZ",NaN,NaN,AZ,4,Both,Conservation,Dept of Interior Secretary Dirk Kempthorne sig...,"All Water Users, Environment",5.0,Scored 5 based on the agreement to protect the...,NaN,0,1,0,3,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0
267,268,USGS301-350.docx,Casa Grande Dispatch (AZ),Arizona plan could devastate Pinal farmers,NaN,2-Feb-19,2019.0,1/31/2019,31.0,1.0,2019.0,N,Y,Entire Colorado River Basin,NaN,"14, 15",State of Arizona,NaN,NaN,AZ,4,Both,Conservation; Ground water depletion,The event is Arizona signing off on the Drough...,"Agriculture, State Government, Federal Government",4.0,Agreement signed and cooperation on all sides...,NaN,1,0,0,10,0,0,0,1,0,0,2,0,0,0,0,0,0,0,0,0

# Part 4: Explore variables

In [39]:
df['Place'].unique()

array(['Durango, CO', 'Great Salt Lake',
       'Colorado River Indian Reservation',
       'Southern Ute Indian Reservation', 'State of Arizona',
       'Entire Colorado River Basin', 'All of Colorado River Basin',
       'Farmington, OH; Great Salt Lake', 'Navajo Nation; Window Rock AZ',
       'Bullhead City, AZ re: All of Colorado R. Basin', 'Phoenix, AZ',
       'Ute Tribe, Utah', 'Denver, CO; Shoshone power plant',
       'AZ, CO, NM, UT, Southern Ute Tribe, Ute Mountain tribe, Navajo Nation',
       'Colorado River Basin', 'Laughlin, AZ',
       'Colorado River Indian Reservation; Parker, AZ',
       'CA - Imperial Irrigation District', 'Flagstaff, AZ',
       'Glen Canyon Dam, Lake Powell, UT; AZ', 'Needles, CA',
       'AZ, NV, Mexico', 'CO, UT, WY, NM', 'Las Vegas, Southern CA; AZ',
       'Sacaton/Gila R. Indian Reservation', 'Boulder, CO', 'Lees Ferry',
       'AZ', 'Lake Powell (UT, AZ)', 'Glenwod Springs',
       'Multiple waterways in UT ', 'St. Michaels, AZ',
       'The Front Range, CO/WY', 'CO', 'Flagstaff, AZ; UT',
       'Las Vegas, Flagstaff, AZ', 'CO (also Phoenix/Tucson, AZ',
       'Window Rock, AZ; Navajo Nation', 'Upper basin states',
       'Greeley, CO', 'AZ, CA, CO, NV, NM, UT, WY',
       'Scottsdale, Tucson, Phoenix, AZ', 'AZ, CA, NV', 'AZ; CA',
       'Las Vegas, NV', 'Hermosa Creek',
       'Phoenix, AZ/AZ; CA; CO, NV; NM; UT, WY', 'Animas River',
       'Lake Mead', 'Long Hollow Dam', 'White River', 'Glendale',
       'Colorado River', 'Southwestern US', 'Garfield County, CO',
       'San Juan River', 'Colorado River System',
       'Navajo Nation, Hopi Reservation', 'Gila River Indian Reservation',
       'Navajo Nation', 'Green River', 'Routt County, CO',
       'Pinal County, AZ', 'Pecos River', 'Colorado State',
       'Navajo/Hopi Reservations, Lower Colorado River', 'Flaming Gorge',
       'Lake Powell', 'Lake Powell, Lake Mead, Gila River',
       'Salt Lake City', 'State of Colorado', 'Pheonix, AZ',
       'Boulder City, NV', 'Salton Sea', 'Mancos River Watershed',
       'California State', 'Washington D.C.', 'Navajo/Hopi Nations',
       'Animas River including Junction and Lightner Creeks from Bakers Bridge to the New Mexico line, La Plata RIver from Mayday to the New Mexico State line, Vellecito Creek, Pine River from Vallecito to the Southern Ute Indian Tribe reservation south of Bayfield, Florida River,',
       'The application for Utah water rights requests 55,000 acre feet of water from the Green River with two pump stations located five miles from the Colorado state line in Dagget County, Utah, on Bureau of Land Management land. The water would then run through a hydroelectric facility before being piped nearly 500 miles northeast into Wyoming and then south down the Colorado Front Range',
       nan, 'Denver, CO', 'Yuma, AZ', 'Yampa Valley, CO', 'Tuscon, AZ',
       'Central Arizona Project, AZ',
       'San Juan County, San Juan River, Navajo Nation',
       'Hoover Dam, Clark County, NV', 'Green River Community, Utah',
       'San Juan River and Lake Powell', 'Navajo Nation, AZ',
       'White Mountain Apache lands Northeast/central AZ, CRIT lands along western edge of AZ and into CA',
       'South of the Seedskadee National Wildlife Refuge',
       'State of California, Nevada, Arizona', 'Glen Canyon Dam',
       'Yuma County, AZ', 'New Mexico, Arizona',
       'Wyoming, Utah, Colorado', 'Glen Canyon Dam, Grand Canyon',
       'Animas River near Silverton, San Juan River to Lake Powell',
       'Meeker, Colorado', 'Arizona ',
       'Arizona, California, Colorado, Nevada, New Mexico, Utah, Wyoming',
       'Lower Basin', 'Navajo Generating Station, near Page, AZ',
       'La Plata County, Animas River Valley', 'Cibola, AZ',
       'Lake Mead; Bullhead City, AZ', 'Colorado River Delta',
       'Little Colorado River Basin', 'State of Utah',
       'San Juan River; Navajo Nation; New Mexico',
       'Colorado; Phoenix AZ', 'Arizona',
       'Wayne County, Utah; Green River',
       'Lower Arkansas Valley Water Conservancy District',
       'Upper Colorado River Basin', 'Green River; Utah',
       'Lower Colorado River Basin', 'Salton Sea; California',
       'Arizona; entire Colorado River Basin',
       'Rio Blanco Water Conservancy District; State of Colorado',
       'Navajo and Hopi Nations/Little Colorado River', 'Bear River',
       'Utah', 'Scottsdale, AZ', 'Colorado ', 'Grand Valley, CO',
       'Austin, TX', 'Western Slope, CO', 'Salt River', 'Green River, UT',
       'Tempe, AZ', 'Yuma, AZ ', 'Glen Canyon Dam, AZ',
       'State of Arizona, State of California'], dtype=object)

In [43]:
df['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

In [44]:
df['Conflict Present'].value_counts()

Conflict Present
Y    145
N    107
Name: count, dtype: int64

# 5. String accessor for pandas.Series

In the following exercises we will work with pandas.Series whose values are strings. This is a common scenario, so pandas has special string methods for this kind of series. These methods are accessed via the str accessor. Accessors provide additional functionality for working with specific kinds of data (in this case, strings).

The code below gives a brief demonstration of using the str accessor to use the split() method for pandas.Series. Carefully read the code.

In [50]:
# CELL 1
import numpy as np
import pandas as pd 

# Example series
new_df = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
new_df

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: object

In [51]:
# CELL 2
# str accessor (doesn't do anything by itself)
new_df.str

In [52]:
# CELL 3
# Use str accessor with additional methods to perform string operations
new_df.str.split(';')

0    [California,  Nevada]
1                [Arizona]
2                      NaN
3          [Nevada,  Utah]
dtype: object

In [54]:
# CELL 4
new_df.str.split(';').explode()

0    California
0        Nevada
1       Arizona
2           NaN
3        Nevada
3          Utah
dtype: object

## 6. Examine state codes

Our goal today is to find which states are reported in the dataset as having water conflicts.

Take a look at the non-NA values in the State column. HINT: notna() method for pandas.Series.

What could be a challenge to finding the states that have reported having water conflicts (without repetition)?

In [58]:
# Non-NA values in the state column
df.loc[df['State'].notna(), "State"]

0          CO
1          CO
2          UT
5          AZ
11     OH; UT
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 178, dtype: object

_A challenge could be double counting a `state` for having more than one non-NA values._

# 8. Exploratory wrangling

a. Perform the following wrangling:

i. select the State column and the rows corresponding to water conflicts occurring

ii. split the strings in the column by the delimiter ;

iii. explode the resulting pandas.Series to have each element of a list as a separate row

iv. find the unique string values in the resulting pandas.Series, keeping the NAs

In [64]:
# Step 1: Select State column where conflict is present
states_conflict = df.loc[df["Conflict Present"] == "Y", "State"]

# Step 2: Split on semicolon delimiter
states_split = states_conflict.str.split(";")
states_split

# Step 3: Explode lists into individual rows
states_exploded = states_split.explode()
states_exploded

# Step 4: Unique values, keeping NAs
states_unique = states_exploded.unique()
states_unique

array(['CO', nan, 'AZ', 'OH', ' UT', 'UT', 'CA', ' NV', ' WY', ' NM',
       ' CA', 'NV', ' AZ', ' CO', 'NM', 'WY'], dtype=object)

In [65]:
# Another way to write the above:

df.loc[df['Conflict Present'] == 'Y', 'State'].str.split(';').explode().unique()

array(['CO', nan, 'AZ', 'OH', ' UT', 'UT', 'CA', ' NV', ' WY', ' NM',
       ' CA', 'NV', ' AZ', ' CO', 'NM', 'WY'], dtype=object)